local ____lualib = include("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 2,["6"] = 2,["7"] = 3,["8"] = 3,["9"] = 5,["10"] = 9,["11"] = 9,["12"] = 13,["13"] = 13,["14"] = 17,["15"] = 17,["16"] = 21,["17"] = 21,["18"] = 26,["19"] = 26,["20"] = 31,["21"] = 31,["22"] = 35,["23"] = 35,["24"] = 37,["25"] = 42,["26"] = 42,["27"] = 47,["28"] = 47,["29"] = 51,["30"] = 51,["31"] = 55,["32"] = 55,["33"] = 59,["34"] = 59,["35"] = 61,["36"] = 65,["37"] = 65,["38"] = 69,["39"] = 69,["40"] = 73,["41"] = 73,["42"] = 77,["43"] = 77,["44"] = 82,["45"] = 82,["46"] = 87,["47"] = 87,["48"] = 91,["49"] = 91,["50"] = 95,["51"] = 95,["52"] = 99,["53"] = 99,["54"] = 103,["55"] = 103,["56"] = 107,["57"] = 107,["58"] = 111,["59"] = 111,["60"] = 115,["61"] = 115,["62"] = 119,["63"] = 119,["64"] = 123,["65"] = 123,["66"] = 127,["67"] = 127,["68"] = 131,["69"] = 131,["70"] = 135,["71"] = 135,["72"] = 139,["73"] = 139,["74"] = 143,["75"] = 143,["76"] = 147,["77"] = 147,["78"] = 235,["79"] = 235,["80"] = 235,["81"] = 240,["82"] = 241,["83"] = 241,["84"] = 241,["85"] = 241,["86"] = 241,["87"] = 241,["88"] = 241,["89"] = 241,["90"] = 241,["91"] = 241,["92"] = 241,["93"] = 241,["94"] = 241,["95"] = 241,["96"] = 241,["97"] = 241,["98"] = 241,["99"] = 241,["100"] = 241,["101"] = 241,["102"] = 241,["103"] = 241,["104"] = 235,["105"] = 235});
local ____exports = {}
local ____DebugEnv = include("logic.debug.DebugEnv")
local debugEnv = ____DebugEnv.debugEnv
local ____SafeTableUtils = include("logic.utils.SafeTableUtils")
local S = ____SafeTableUtils.S
____exports.GameMode = GameMode or ({})
____exports.GameMode.NORMAL = 1
____exports.GameMode[____exports.GameMode.NORMAL] = "NORMAL"
____exports.GameMode.ELITE = 2
____exports.GameMode[____exports.GameMode.ELITE] = "ELITE"
____exports.GameMode.KOF = 3
____exports.GameMode[____exports.GameMode.KOF] = "KOF"
____exports.GameMode["镜像"] = 4
____exports.GameMode[____exports.GameMode["镜像"]] = "镜像"
____exports.GameMode["兔羊大战"] = 5
____exports.GameMode[____exports.GameMode["兔羊大战"]] = "兔羊大战"
____exports.GameMode["三v三混战"] = 6
____exports.GameMode[____exports.GameMode["三v三混战"]] = "三v三混战"
____exports.GameMode["终极大战"] = 7
____exports.GameMode[____exports.GameMode["终极大战"]] = "终极大战"
____exports.GameStatus = GameStatus or ({})
____exports.GameStatus["选大祝福"] = 0
____exports.GameStatus[____exports.GameStatus["选大祝福"]] = "选大祝福"
____exports.GameStatus["选人阶段"] = 1
____exports.GameStatus[____exports.GameStatus["选人阶段"]] = "选人阶段"
____exports.GameStatus["准备回合"] = 2
____exports.GameStatus[____exports.GameStatus["准备回合"]] = "准备回合"
____exports.GameStatus["战斗中"] = 3
____exports.GameStatus[____exports.GameStatus["战斗中"]] = "战斗中"
____exports.GameStatus["游戏结束"] = 4
____exports.GameStatus[____exports.GameStatus["游戏结束"]] = "游戏结束"
____exports.GameRandomEventType = GameRandomEventType or ({})
____exports.GameRandomEventType["无事件"] = 0
____exports.GameRandomEventType[____exports.GameRandomEventType["无事件"]] = "无事件"
____exports.GameRandomEventType["刺客"] = 1
____exports.GameRandomEventType[____exports.GameRandomEventType["刺客"]] = "刺客"
____exports.GameRandomEventType["金币怪"] = 2
____exports.GameRandomEventType[____exports.GameRandomEventType["金币怪"]] = "金币怪"
____exports.GameRandomEventType["木头怪"] = 3
____exports.GameRandomEventType[____exports.GameRandomEventType["木头怪"]] = "木头怪"
____exports.GameRandomEventType["双倍怪物"] = 4
____exports.GameRandomEventType[____exports.GameRandomEventType["双倍怪物"]] = "双倍怪物"
____exports.GameRandomEventType["福利怪入侵"] = 5
____exports.GameRandomEventType[____exports.GameRandomEventType["福利怪入侵"]] = "福利怪入侵"
____exports.GameRandomEventType["死亡自爆"] = 6
____exports.GameRandomEventType[____exports.GameRandomEventType["死亡自爆"]] = "死亡自爆"
____exports.GameRandomEventType["闪电战"] = 7
____exports.GameRandomEventType[____exports.GameRandomEventType["闪电战"]] = "闪电战"
____exports.GameRandomEventType["炮车怪"] = 8
____exports.GameRandomEventType[____exports.GameRandomEventType["炮车怪"]] = "炮车怪"
____exports.GameRandomEventType["艰苦抉择"] = 9
____exports.GameRandomEventType[____exports.GameRandomEventType["艰苦抉择"]] = "艰苦抉择"
____exports.GameRandomEventType["佣兵狂潮"] = 10
____exports.GameRandomEventType[____exports.GameRandomEventType["佣兵狂潮"]] = "佣兵狂潮"
____exports.GameRandomEventType["真男人大战"] = 11
____exports.GameRandomEventType[____exports.GameRandomEventType["真男人大战"]] = "真男人大战"
____exports.GameRandomEventType["随机虫洞"] = 12
____exports.GameRandomEventType[____exports.GameRandomEventType["随机虫洞"]] = "随机虫洞"
____exports.GameRandomEventType["内奸行为"] = 13
____exports.GameRandomEventType[____exports.GameRandomEventType["内奸行为"]] = "内奸行为"
____exports.GameRandomEventType["宠物收集师"] = 14
____exports.GameRandomEventType[____exports.GameRandomEventType["宠物收集师"]] = "宠物收集师"
____exports.GameRandomEventType["无限火力"] = 15
____exports.GameRandomEventType[____exports.GameRandomEventType["无限火力"]] = "无限火力"
____exports.GameRandomEventType["疯狂进攻"] = 16
____exports.GameRandomEventType[____exports.GameRandomEventType["疯狂进攻"]] = "疯狂进攻"
____exports.GameRandomEventType["雷击"] = 17
____exports.GameRandomEventType[____exports.GameRandomEventType["雷击"]] = "雷击"
____exports.GameRandomEventType["超人体验卡"] = 18
____exports.GameRandomEventType[____exports.GameRandomEventType["超人体验卡"]] = "超人体验卡"
____exports.GameRandomEventType["御驾亲征"] = 19
____exports.GameRandomEventType[____exports.GameRandomEventType["御驾亲征"]] = "御驾亲征"
____exports.GameRandomEventType["混乱伤害"] = 20
____exports.GameRandomEventType[____exports.GameRandomEventType["混乱伤害"]] = "混乱伤害"
____exports.GameData = {
    name = "GameData",
    indexKeys = {},
    make = function(self)
        return S({
            isEnterGame = false,
            level = 0,
            runningLevel = 0,
            mode = ____exports.GameMode.NORMAL,
            isEnd = false,
            skipReady = false,
            startTime = 0,
            leftMonster = 0,
            teamALeftMonster = 0,
            teamBLeftMonster = 0,
            teamALeftPlayerCount = 0,
            teamBLeftPlayerCount = 0,
            isInitTeam = false,
            teamLeft = {},
            teamRight = {},
            blessRule = 0,
            randomEventType = 0,
            gameStatus = debugEnv.enableBigBless and ____exports.GameStatus["选大祝福"] or ____exports.GameStatus["选人阶段"],
            gameStartFrame = 0,
            aiDifficulty = "easy"
        })
    end
}
return ____exports
