local ____lualib = include("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 73,["6"] = 74,["7"] = 74,["8"] = 75,["9"] = 75,["10"] = 76,["11"] = 76,["12"] = 77,["13"] = 77,["14"] = 78,["15"] = 78,["16"] = 79,["17"] = 79,["18"] = 80,["19"] = 80,["20"] = 81,["21"] = 81,["22"] = 82,["23"] = 82,["24"] = 83,["25"] = 83,["26"] = 84,["27"] = 84,["28"] = 85,["29"] = 85,["30"] = 103,["31"] = 104,["32"] = 104,["33"] = 105,["34"] = 105,["35"] = 106,["36"] = 106,["37"] = 107,["38"] = 107,["39"] = 108,["40"] = 108,["41"] = 109,["42"] = 109,["43"] = 110,["44"] = 110,["45"] = 111,["46"] = 111,["47"] = 112,["48"] = 112,["49"] = 113,["50"] = 113,["51"] = 115,["52"] = 115,["53"] = 116,["54"] = 116,["55"] = 117,["56"] = 117,["57"] = 118,["58"] = 118,["59"] = 119,["60"] = 119,["61"] = 122,["62"] = 123,["63"] = 123,["64"] = 124,["65"] = 124,["66"] = 127,["67"] = 128,["68"] = 128,["69"] = 130,["70"] = 130,["71"] = 131,["72"] = 131,["73"] = 132,["74"] = 132,["75"] = 133,["76"] = 133,["77"] = 134,["78"] = 134,["79"] = 135,["80"] = 135,["81"] = 136,["82"] = 136,["83"] = 137,["84"] = 137,["85"] = 138,["86"] = 138,["87"] = 141,["88"] = 142,["89"] = 142,["90"] = 143,["91"] = 143,["92"] = 144,["93"] = 144,["94"] = 145,["95"] = 145,["96"] = 146,["97"] = 146,["98"] = 147,["99"] = 147,["100"] = 148,["101"] = 148,["102"] = 149,["103"] = 149,["104"] = 150,["105"] = 150,["106"] = 151,["107"] = 151,["108"] = 152,["109"] = 152,["110"] = 153,["111"] = 153,["112"] = 154,["113"] = 154,["114"] = 155,["115"] = 155,["116"] = 158,["117"] = 158,["118"] = 159,["119"] = 159,["120"] = 160,["121"] = 160,["122"] = 161,["123"] = 161,["124"] = 162,["125"] = 162,["126"] = 163,["127"] = 163,["128"] = 164,["129"] = 164,["130"] = 166,["131"] = 166,["133"] = 241,["134"] = 242,["135"] = 242,["136"] = 242,["137"] = 242,["138"] = 242,["139"] = 242,["140"] = 242,["141"] = 242,["142"] = 242,["143"] = 242,["144"] = 242,["145"] = 242,["146"] = 242,["147"] = 242,["148"] = 242,["149"] = 242,["150"] = 242,["151"] = 242,["152"] = 242,["153"] = 241,["154"] = 241,["155"] = 241,["156"] = 241,["157"] = 241,["158"] = 241,["159"] = 241,["160"] = 241,["161"] = 241,["162"] = 241});
local ____exports = {}
____exports.SettingType = SettingType or ({})
____exports.SettingType["Null_空"] = 0
____exports.SettingType[____exports.SettingType["Null_空"]] = "Null_空"
____exports.SettingType["Hero_英雄"] = 1
____exports.SettingType[____exports.SettingType["Hero_英雄"]] = "Hero_英雄"
____exports.SettingType["Shop_商店"] = 2
____exports.SettingType[____exports.SettingType["Shop_商店"]] = "Shop_商店"
____exports.SettingType["Bag_背包"] = 3
____exports.SettingType[____exports.SettingType["Bag_背包"]] = "Bag_背包"
____exports.SettingType["Mail_邮件"] = 4
____exports.SettingType[____exports.SettingType["Mail_邮件"]] = "Mail_邮件"
____exports.SettingType["Wiki_图鉴"] = 5
____exports.SettingType[____exports.SettingType["Wiki_图鉴"]] = "Wiki_图鉴"
____exports.SettingType["Rank_排行榜"] = 6
____exports.SettingType[____exports.SettingType["Rank_排行榜"]] = "Rank_排行榜"
____exports.SettingType["Decoration_装饰"] = 7
____exports.SettingType[____exports.SettingType["Decoration_装饰"]] = "Decoration_装饰"
____exports.SettingType["Achieve_成就"] = 8
____exports.SettingType[____exports.SettingType["Achieve_成就"]] = "Achieve_成就"
____exports.SettingType["Life_生涯"] = 9
____exports.SettingType[____exports.SettingType["Life_生涯"]] = "Life_生涯"
____exports.SettingType["Match_比赛"] = 10
____exports.SettingType[____exports.SettingType["Match_比赛"]] = "Match_比赛"
____exports.SettingType["Honor_荣誉"] = 11
____exports.SettingType[____exports.SettingType["Honor_荣誉"]] = "Honor_荣誉"
____exports.ShopType = ShopType or ({})
____exports.ShopType["Hero_金币商城英雄"] = 1
____exports.ShopType[____exports.ShopType["Hero_金币商城英雄"]] = "Hero_金币商城英雄"
____exports.ShopType["Skin_钻石商城皮肤"] = 2
____exports.ShopType[____exports.ShopType["Skin_钻石商城皮肤"]] = "Skin_钻石商城皮肤"
____exports.ShopType["Decoration_钻石商城装饰"] = 3
____exports.ShopType[____exports.ShopType["Decoration_钻石商城装饰"]] = "Decoration_钻石商城装饰"
____exports.ShopType["Item_钻石商城道具"] = 4
____exports.ShopType[____exports.ShopType["Item_钻石商城道具"]] = "Item_钻石商城道具"
____exports.ShopType["PetSkill_宠物技能"] = 5
____exports.ShopType[____exports.ShopType["PetSkill_宠物技能"]] = "PetSkill_宠物技能"
____exports.ShopType["MercenarySkill_佣兵皮肤"] = 6
____exports.ShopType[____exports.ShopType["MercenarySkill_佣兵皮肤"]] = "MercenarySkill_佣兵皮肤"
____exports.ShopType["KK_KK商城U币"] = 7
____exports.ShopType[____exports.ShopType["KK_KK商城U币"]] = "KK_KK商城U币"
____exports.ShopType["KK_KK商城金币"] = 8
____exports.ShopType[____exports.ShopType["KK_KK商城金币"]] = "KK_KK商城金币"
____exports.ShopType["KK_KK商城积分"] = 9
____exports.ShopType[____exports.ShopType["KK_KK商城积分"]] = "KK_KK商城积分"
____exports.ShopType["Item_金币商城道具"] = 10
____exports.ShopType[____exports.ShopType["Item_金币商城道具"]] = "Item_金币商城道具"
____exports.ShopType.STEAM_TOP_UP = 101
____exports.ShopType[____exports.ShopType.STEAM_TOP_UP] = "STEAM_TOP_UP"
____exports.ShopType.STEAM_LOTTERY = 102
____exports.ShopType[____exports.ShopType.STEAM_LOTTERY] = "STEAM_LOTTERY"
____exports.ShopType.STEAM_MONTH_CARD = 103
____exports.ShopType[____exports.ShopType.STEAM_MONTH_CARD] = "STEAM_MONTH_CARD"
____exports.ShopType.STEAM_POINT = 104
____exports.ShopType[____exports.ShopType.STEAM_POINT] = "STEAM_POINT"
____exports.ShopType.STEAM_COUPON = 105
____exports.ShopType[____exports.ShopType.STEAM_COUPON] = "STEAM_COUPON"
____exports.AchieveType = AchieveType or ({})
____exports.AchieveType["Map_地图"] = 1
____exports.AchieveType[____exports.AchieveType["Map_地图"]] = "Map_地图"
____exports.AchieveType["Game_游戏"] = 0
____exports.AchieveType[____exports.AchieveType["Game_游戏"]] = "Game_游戏"
____exports.DecorationType = DecorationType or ({})
____exports.DecorationType["HeroSkin_英雄皮肤"] = 1
____exports.DecorationType[____exports.DecorationType["HeroSkin_英雄皮肤"]] = "HeroSkin_英雄皮肤"
____exports.DecorationType["MercenarySkin_佣兵皮肤"] = 2
____exports.DecorationType[____exports.DecorationType["MercenarySkin_佣兵皮肤"]] = "MercenarySkin_佣兵皮肤"
____exports.DecorationType["Pet_宠物"] = 3
____exports.DecorationType[____exports.DecorationType["Pet_宠物"]] = "Pet_宠物"
____exports.DecorationType["PetWing_宠物翅膀"] = 4
____exports.DecorationType[____exports.DecorationType["PetWing_宠物翅膀"]] = "PetWing_宠物翅膀"
____exports.DecorationType["PetHalo_宠物光环"] = 5
____exports.DecorationType[____exports.DecorationType["PetHalo_宠物光环"]] = "PetHalo_宠物光环"
____exports.DecorationType["PetEffect_宠物粒子"] = 6
____exports.DecorationType[____exports.DecorationType["PetEffect_宠物粒子"]] = "PetEffect_宠物粒子"
____exports.DecorationType["PetSkill_宠物技能"] = 7
____exports.DecorationType[____exports.DecorationType["PetSkill_宠物技能"]] = "PetSkill_宠物技能"
____exports.DecorationType["PetTitle_称谓"] = 8
____exports.DecorationType[____exports.DecorationType["PetTitle_称谓"]] = "PetTitle_称谓"
____exports.DecorationType["PetEmo_宠物表情"] = 9
____exports.DecorationType[____exports.DecorationType["PetEmo_宠物表情"]] = "PetEmo_宠物表情"
____exports.DecorationType["HallBg_大厅背景"] = 10
____exports.DecorationType[____exports.DecorationType["HallBg_大厅背景"]] = "HallBg_大厅背景"
____exports.GuideProgress = GuideProgress or ({})
____exports.GuideProgress.None = 0
____exports.GuideProgress[____exports.GuideProgress.None] = "None"
____exports.GuideProgress.Guide_1_0 = 1
____exports.GuideProgress[____exports.GuideProgress.Guide_1_0] = "Guide_1_0"
____exports.GuideProgress.Guide_1_1 = 2
____exports.GuideProgress[____exports.GuideProgress.Guide_1_1] = "Guide_1_1"
____exports.GuideProgress.Guide_1_2 = 3
____exports.GuideProgress[____exports.GuideProgress.Guide_1_2] = "Guide_1_2"
____exports.GuideProgress.Guide_1_3 = 4
____exports.GuideProgress[____exports.GuideProgress.Guide_1_3] = "Guide_1_3"
____exports.GuideProgress.Guide_1_4 = 5
____exports.GuideProgress[____exports.GuideProgress.Guide_1_4] = "Guide_1_4"
____exports.GuideProgress.None_2 = 6
____exports.GuideProgress[____exports.GuideProgress.None_2] = "None_2"
____exports.GuideProgress.Guide_2_1 = 7
____exports.GuideProgress[____exports.GuideProgress.Guide_2_1] = "Guide_2_1"
____exports.GuideProgress.Guide_2_2 = 8
____exports.GuideProgress[____exports.GuideProgress.Guide_2_2] = "Guide_2_2"
____exports.GuideProgress.Guide_2_3 = 9
____exports.GuideProgress[____exports.GuideProgress.Guide_2_3] = "Guide_2_3"
____exports.GuideProgress.Guide_2_4 = 10
____exports.GuideProgress[____exports.GuideProgress.Guide_2_4] = "Guide_2_4"
____exports.GuideProgress.None_3 = 11
____exports.GuideProgress[____exports.GuideProgress.None_3] = "None_3"
____exports.GuideProgress.Guide_3_1 = 12
____exports.GuideProgress[____exports.GuideProgress.Guide_3_1] = "Guide_3_1"
____exports.GuideProgress.Guide_3_2 = 13
____exports.GuideProgress[____exports.GuideProgress.Guide_3_2] = "Guide_3_2"
____exports.GuideProgress.None_4 = 14
____exports.GuideProgress[____exports.GuideProgress.None_4] = "None_4"
____exports.GuideProgress.Guide_4_1 = 15
____exports.GuideProgress[____exports.GuideProgress.Guide_4_1] = "Guide_4_1"
____exports.GuideProgress.Guide_4_2 = 16
____exports.GuideProgress[____exports.GuideProgress.Guide_4_2] = "Guide_4_2"
____exports.GuideProgress.Guide_4_3 = 17
____exports.GuideProgress[____exports.GuideProgress.Guide_4_3] = "Guide_4_3"
____exports.GuideProgress.Guide_4_4 = 18
____exports.GuideProgress[____exports.GuideProgress.Guide_4_4] = "Guide_4_4"
____exports.GuideProgress.None_5 = 19
____exports.GuideProgress[____exports.GuideProgress.None_5] = "None_5"
____exports.GuideProgress.Guide_6_1 = 20
____exports.GuideProgress[____exports.GuideProgress.Guide_6_1] = "Guide_6_1"
____exports.GuideProgress.Complete = 100
____exports.GuideProgress[____exports.GuideProgress.Complete] = "Complete"
--- 本地数据，一般用于UI相关的跨界面操作
____exports.localData = vue.reactive({
    main = {
        showCard = false,
        showCarding = false,
        showMercenary = false,
        showMercenarying = false,
        showMercenaryTips = false,
        showBless = false,
        showBlessing = false,
        showTalent = false,
        showTalenting = false,
        showWave = false,
        showDamageStat = false,
        showRecommand = false,
        recommand = 1,
        mercenaryLevel = 1,
        addExp = 0,
        progress1 = 0,
        progress2 = 0,
        technologyIng = false
    },
    setting = {showDetail = false, tabIndex = ____exports.SettingType["Null_空"]},
    shop = {tabIndex = ____exports.ShopType["Hero_金币商城英雄"], subTabIndex = 0},
    decoration = {tabIndex = ____exports.DecorationType["HeroSkin_英雄皮肤"], subTabIndex = 0},
    achieve = {tabIndex = ____exports.AchieveType["Map_地图"], subTabIndex = 0},
    guide = ____exports.GuideProgress.None,
    inGameHall = false,
    isFirst = false,
    rewards = {}
})
return ____exports
